app/admin/manage_user/__init__.py
from app.admin.manage_user.views import manage_user  # noqa

app/admin/views.py
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for, jsonify)
from flask_login import current_user, login_required

from app import db
from app.admin.forms import (NewUserForm, ConfirmForm, FileUpload)
from app.decorators import admin_required
from app.models import (EditableHTML, Role, User, User_schedule, Shift,
                        Schedule_year, Timeoff, Team, Timeoff_Type, Import_log)
from app.admin.utils.staffhub_import import Shifts_Import, TimeOff_Import
from datetime import timedelta, datetime
import subprocess

admin = Blueprint('admin', __name__)


def backup_db():
    subprocess.call(
        'C:\\Users\\csaretzky\\staff_tracker\\StaffTracker\\backup\\backup.bat'
    )


def import_schedule_data(file, year):
    shift_imp = Shifts_Import(file, year)
    if not shift_imp.isValidated:
        return shift_imp.log
    else:
        backup_db()
        rec_range = [
            shift_imp.valid_data[0]['shiftstart'],
            shift_imp.valid_data[len(shift_imp.valid_data) - 1]['shiftend']
        ]
        db.session.query(Shift).filter(Shift.start >= rec_range[0]).filter(
            Shift.end <= rec_range[1]).filter(
                Shift.manual_edit == False).delete()
        db.session.commit()

        for d in shift_imp.valid_data:
            user = User.query.filter_by(first_name=d['first_name']).filter_by(
                last_name=d['last_name']).first()
            if user:
                schedule_year = Schedule_year.query.filter_by(
                    year=year).first()
                user_schedule = User_schedule.query.filter_by(
                    user=user, year=schedule_year).first()
                if user_schedule:
                    shift = Shift(
                        schedule=user_schedule,
                        start=d['shiftstart'],
                        end=d['shiftend'],
                        isic=d['isic'],
                        training=d['training'],
                        otbanked=d['otbanked'],
                        otpaid=d['otpaidout'],
                        comment=d['comment'])
                    db.session.add(shift)

        timeoff_imp = TimeOff_Import(file, year)
        rec_range = [
            timeoff_imp.valid_data[0]['dayof'],
            timeoff_imp.valid_data[len(timeoff_imp.valid_data) - 1]['dayof']
        ]

        db.session.query(Timeoff).filter(Timeoff.dayof >= rec_range[0]).filter(
            Timeoff.dayof <= rec_range[1]).delete()
        db.session.commit()

        for d in timeoff_imp.valid_data:
            user = User.query.filter_by(first_name=d['first_name']).filter_by(
                last_name=d['last_name']).first()
            if user:
                schedule_year = Schedule_year.query.filter_by(
                    year=year).first()
                user_schedule = User_schedule.query.filter_by(
                    user=user, year=schedule_year).first()
                if user_schedule:
                    timeoff = Timeoff(
                        schedule=user_schedule,
                        dayof=d['dayof'],
                        partialtime=d['partialtime'],
                        type=Timeoff_Type.query.filter_by(
                            name=d['type']).first())
                    db.session.add(timeoff)
        log = Import_log(
            run_date=datetime.now(),
            start=rec_range[0],
            end=rec_range[1],
            schema_errors=shift_imp.log['schema_errors'],
            invalid_colors=shift_imp.log['invalid_colors'],
            invalid_times=shift_imp.log['invalid_times'],
            invalid_header=shift_imp.log['invalid_header'],
            records=shift_imp.log['records'],
            dates=shift_imp.log['dates'],
            employees=shift_imp.log['employees'],
            _type=shift_imp.log['type'])
        db.session.add(log)
        db.session.commit()
        return None


@admin.route('/')
@login_required
@admin_required
def index():
    cnt_unconf_users = User.query.filter_by(confirmed=False).filter_by(
        active=True).count()
    return render_template(
        'admin/index.html', cnt_unconf_users=cnt_unconf_users)


@admin.route('/new-user', methods=['GET', 'POST'])
@login_required
@admin_required
def new_user():
    """Create a new user."""
    form = NewUserForm(team=Team.query.filter_by(name='SC').first())
    if form.validate_on_submit():
        user = User(
            role=form.role.data,
            team=form.team.data,
            confirmed=True,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            password=form.password.data,
            username=form.email.data,
            start_date=form.startdate.data,
            change_pw=True)
        user_schedule = User_schedule(
            user=user,
            year=Schedule_year.query.filter_by(iscurrent=True).first(),
            active=True,
            carriedvacation=form.carriedvacation.data,
            entitledvacation=form.entitledvacation.data,
            entitledpersonal=form.entitledpersonal.data,
            isparttime=form.isparttime.data,
            isaveraging=form.isaveraging.data,
            shiftlength=form.shiftlength.data,
            notes=form.notes.data)
        db.session.add(user)
        db.session.add(user_schedule)
        db.session.commit()
        flash('User {} successfully created'.format(user.full_name()),
              'success')
        return redirect(url_for('admin.index'))
    return render_template('admin/new_user.html', form=form)


@admin.route('/users')
@login_required
@admin_required
def registered_users():
    """View all registered users."""
    users = User.query.filter_by(confirmed=True).all()
    roles = Role.query.all()
    teams = Team.query.all()
    return render_template(
        'admin/registered_users.html', users=users, roles=roles, teams=teams)



@admin.route('/shift_info', methods=['GET', 'POST'])
@login_required
@admin_required
def shift_info():
    roles = Role.query.all()
    teams = Team.query.all()
    years = Schedule_year.query.order_by(Schedule_year.iscurrent.desc()).all()

    if request.method == 'POST':
        year_id = request.form['year']
    else:
        year_id = Schedule_year.query.filter_by(iscurrent=True).first().id
    year_id = 1

    shift_qry = db.session.query(Shift). \
                join(User_schedule). \
                join(User). \
                join(Team). \
                join(Role). \
                join(Schedule_year). \
                filter(Schedule_year.id == year_id)

    shift_low = shift_qry.order_by(Shift.start.asc()).first()
    shift_high = shift_qry.order_by(Shift.end.desc()).first()
    weeks = get_weeks(shift_low.start, shift_high.end)
    week_stats = []
    for w in weeks:
        w_stats = {
            'week':w[0].strftime('%x'),
            'SC_R':0,
            'SC_IC':0,
            'SC_OTB':0,
            'SC_OTP':0,
            'SC_T':0,
            'SC_ADMIN': 0,
            'CS_R':0,
            'CS_ADMIN':0,
            'ES_R':0,
            'ES_ADMIN':0,
            'ATS_R':0,
            'ATS_ADMIN':0
        }
        qry = shift_qry.filter(Shift.start >= w[0]).filter(Shift.end <= w[1]).all()
        for r in qry:
            if r.schedule.user.team.name == 'SC':
                if r.schedule.user.role.name == 'Administrator':
                    w_stats['SC_ADMIN'] += r.hours
                if r.isic:
                    w_stats['SC_IC'] += r.hours
                if r.otbanked:
                    w_stats['SC_OTB'] += r.hours
                if r.otpaid:
                    w_stats['SC_OTP'] += r.hours
                if r.training:
                    w_stats['SC_T'] += r.hours
                w_stats['SC_R'] += r.hours
            if r.schedule.user.team.name == 'CS':
                if r.schedule.user.role.name == 'Administrator':
                    w_stats['CS_ADMIN'] += r.hours
                w_stats['CS_R'] += r.hours
            if r.schedule.user.team.name == 'ES':
                if r.schedule.user.role.name == 'Administrator':
                    w_stats['ES_ADMIN'] += r.hours
                w_stats['ES_R'] += r.hours
            if r.schedule.user.team.name == 'ATS':
                if r.schedule.user.role.name == 'Administrator':
                    w_stats['ATS_ADMIN'] += r.hours
                w_stats['ATS_R'] += r.hours
            
        week_stats.append(w_stats)
    return render_template(
        'admin/shift_info.html', week_stats=week_stats, roles=roles, teams=teams, years=years)

def get_weeks(start, end):
    weeks = []
    if start.isoweekday() == 7:
        week_e = start + timedelta(6)
        weeks.append((start, week_e))
    else:
        week_e = start + timedelta(6 - start.isoweekday())
        weeks.append((start, start + timedelta(6)))
    
    d_iter = week_e + timedelta(1)
    while(d_iter < end):
        week_e = d_iter + timedelta(6)
        weeks.append((d_iter, week_e))
        d_iter = week_e + timedelta(1)
    return weeks
        


@admin.route('/timeoff_info')
@login_required
@admin_required
def timeoff_info():
    timeoff = db.session.query(Timeoff).join(User_schedule).join(
        Schedule_year).filter(Schedule_year.iscurrent == True).all()
    return render_template('admin/timeoff_info.html', timeoff=timeoff)


@admin.route('/unconfirmed_users')
@login_required
@admin_required
def unconfirmed_users():
    """View all registered users."""
    users = User.query.filter_by(confirmed=False).all()
    if len(users) == 0:
        flash('No unconfirmed users', 'warning')
        return redirect(url_for('admin.index'))
    return render_template('admin/unconfirmed_users.html', users=users)


@admin.route('/user/<int:user_id>/confirm', methods=['GET', 'POST'])
@login_required
@admin_required
def confirm_user(user_id):
    form = ConfirmForm()

app/user/__init__.py
from app.user.views import user  # noqa

app/user/views.py
from flask import Blueprint, render_template, url_for, redirect

from app import db
from flask_login import (current_user, login_required)
from app.models import User, Schedule_year, Shift, User_schedule, Timeoff

user = Blueprint('user', __name__)


@user.route('/')
@login_required
def index():
    user = User.query.filter_by(id=current_user.id).first()
    schedules = User_schedule.query.filter_by(user=user)
    return render_template('user/index.html', user=user, schedules=schedules)

@user.route('/schedule/<int:schedule_id>')
@login_required
def schedule(schedule_id):
    user = User.query.filter_by(id=current_user.id).first()
    schedule = User_schedule.query.filter_by(user=user).filter_by(id=schedule_id).first()
    if schedule is None:
        return redirect(url_for('user.index'))
    return render_template('user/schedule.html', user=user, schedule=schedule)


@user.route('/shift_info')
@login_required
def shift_info():
    user = User.query.filter_by(id=current_user.id).first()
    schedule = db.session.query(User_schedule).join(
        Schedule_year, User_schedule.year).filter(
            Schedule_year.iscurrent).filter(
                User_schedule.user == user).first()
    if schedule is None:
        return redirect(url_for('user.index'))
    else:
        shifts = Shift.query.filter_by(schedule=schedule).all()
        return render_template(
            'user/shift_info.html', user=user, shifts=shifts)


@user.route('/timeoff_info')
@login_required
def timeoff_info():
    user = User.query.filter_by(id=current_user.id).first()
    schedule = User_schedule.query.filter_by(user=user).filter_by(
        active=True).first()
    if schedule is None:
        return redirect(url_for('user.index'))
    else:
        timeoff = Timeoff.query.filter_by(schedule=schedule).all()
        return render_template(
            'user/timeoff_info.html', user=user, timeoff=timeoff)

app/templates/layouts/base.html
{% import 'macros/nav_macros.html' as nav %}

<!DOCTYPE html>
<html>
    <head>
        {% include 'partials/_head.html' %}
        {# Any templates that extend this template can set custom_head_tags to add scripts to their page #}
        {% block custom_head_tags %}{% endblock %}
    </head>
    <body>
      {# Example dropdown menu setup. Uncomment lines to view
        {% set dropdown =
          [
            ('account stuff',
              [
                ('account.login', 'login', 'sign in'),
                ('account.logout', 'logout', 'sign out'),
                ('2nd drop', [
                  ('account.login', 'login 2', ''),
                  ('3rd drop', [
                    ('main.index', 'home 2', '')
                  ])
                ])
              ]
            ),
            ('main.index', 'home 1', 'home')
          ]
        %}
      #}

        {% block nav %}
          {# add dropdown variable here to the render_nav method to render dropdowns #}
          {{ nav.render_nav(current_user) }}
        {% endblock %}

        {% include 'partials/_flashes.html' %}
        {# When extended, the content block contains all the html of the webpage #}
        {% block content %}
        {% endblock %}

        {# Implement CSRF protection for site #}
        {% if csrf_token()|safe %}
            <div style="visibility: hidden; display: none">
              <input type="hidden" name="csrf_token" value="{{ csrf_token()|safe }}">
            </div>
        {% endif %}
    </body>
</html>

app/templates/layouts/manage_user.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% if user.active %}
    {% set endpoints = [
        ('manage_user.user_info', 'User information'),
        ('manage_user.shift_info', 'Shift Information'),
        ('manage_user.timeoff_info', 'Time Off Information'),
        ('manage_user.change_team', 'Change Team'),
        ('manage_user.change_account_type', 'Change Account Type'),
        ('manage_user.deactivate_user', 'Deactivate User')
    ] %}
{% else %}
    {% set endpoints = [
        ('manage_user.reactivate_user', 'Reactivate User')
    ] %}
{% endif %}


{% macro navigation(items) %}
    <div class="ui vertical fluid secondary menu">
        {% for route, name in items %}
            {% set href = url_for(route, user_id=user.id) %}
            <a class="item {% if request.endpoint == route %}active{% endif %}" href="{{ href }}">
                {{ name }}
            </a>
        {% endfor %}
    </div>
{% endmacro %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('admin.registered_users') }}">
                <i class="caret left icon"></i>
                Back to all users
            </a>
            <h2 class="ui header">
                {{ user.full_name() }}
                <div class="sub header">View and manage {{ user.first_name }}’s account.</div>
            </h2>
        </div>
        <div class="stretched divided very relaxed row">
            <div class="four wide column">
                {{ navigation(endpoints) }}
            </div>
            <div class="eight wide column">
                {% block manage_user %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/layouts/user.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% set endpoints = [
    ('user.index', 'User information'),
    ('user.shift_info', 'Shift Information'),
    ('user.timeoff_info', 'Time Off Information'),
] %}


{% macro navigation(items) %}
    <div class="ui vertical fluid secondary menu">
        {% for route, name in items %}
            {% set href = url_for(route) %}
            <a class="item {% if request.endpoint == route %}active{% endif %}" href="{{ href }}">
                {{ name }}
            </a>
        {% endfor %}
    </div>
{% endmacro %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <h2 class="ui header">
                {{ user.full_name() }}
            </h2>
        </div>
        <div class="stretched divided very relaxed row">
            <div class="four wide column">
                {{ navigation(endpoints) }}
            </div>
            <div class="eight wide column">
                {% block user %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}