app/models/user.py
from flask import current_app
from flask_login import AnonymousUserMixin, UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import BadSignature, SignatureExpired
from werkzeug.security import check_password_hash, generate_password_hash

from .. import db, login_manager


class Permission:
    GENERAL = 0x01
    ADMINISTER = 0xff


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    index = db.Column(db.String(64))
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role', lazy='dynamic')

    @staticmethod
    def insert_roles():
        roles = {
            'User': (Permission.GENERAL, 'main', True),
            'Administrator': (
                Permission.ADMINISTER,
                'admin',
                False  # grants all permissions
            )
        }
        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role(name=r)
            role.permissions = roles[r][0]
            role.index = roles[r][1]
            role.default = roles[r][2]
            db.session.add(role)
        db.session.commit()

    def __repr__(self):
        return '<Role \'%s\'>' % self.name


class Team(db.Model):
    __tablename__ = 'teams'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='team', lazy='dynamic')

    @staticmethod
    def insert_teams():
        teams = {'SC', 'ES', 'CS', 'ATS'}
        for t in teams:
            team = Team.query.filter_by(name=t).first()
            if team is None:
                team = Team(name=t)
                db.session.add(team)
        db.session.commit()

    def __repr__(self):
        return '<Team \'%s\'>' % self.name


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    confirmed = db.Column(db.Boolean, default=False)
    first_name = db.Column(db.String(64), index=True)
    last_name = db.Column(db.String(64), index=True)
    _username = db.Column(db.String)
    email = db.Column(db.String(64), unique=True, index=True)
    phone = db.Column(db.String)
    password_hash = db.Column(db.String(128))
    change_pw = db.Column(db.Boolean)
    active = db.Column(db.Boolean, default=True)
    start_date = db.Column(db.Date)
    term_date = db.Column(db.Date)
    schedules = db.relationship('User_schedule', backref='user')
    payrolls = db.relationship('User_payroll', backref='user')
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    team_id = db.Column(db.Integer, db.ForeignKey('teams.id'))

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['ADMIN_EMAIL']:
                self.role = Role.query.filter_by(
                    permissions=Permission.ADMINISTER).first()
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()

    def full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def can(self, permissions):
        return self.role is not None and \
            (self.role.permissions & permissions) == permissions

    def is_admin(self):
        return self.can(Permission.ADMINISTER)

    @property
    def password(self):
        raise AttributeError('`password` is not a readable attribute')

    @property
    def username(self):
        return self._username

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    @username.setter
    def username(self, data):
        self._username = data.split('@')[0]

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=604800):
        """Generate a confirmation token to email a new user."""

        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def generate_email_change_token(self, new_email, expiration=3600):
        """Generate an email change token to email an existing user."""
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'change_email': self.id, 'new_email': new_email})

    def generate_password_reset_token(self, expiration=3600):
        """
        Generate a password reset change token to email to an existing user.
        """
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'reset': self.id})

    def confirm_account(self, token):
        """Verify that the provided token is for this user's id."""
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except (BadSignature, SignatureExpired):
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        db.session.commit()
        return True

    def change_email(self, token):
        """Verify the new email for this user."""
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except (BadSignature, SignatureExpired):
            return False
        if data.get('change_email') != self.id:
            return False
        new_email = data.get('new_email')
        if new_email is None:
            return False
        if self.query.filter_by(email=new_email).first() is not None:
            return False
        self.email = new_email
        db.session.add(self)
        db.session.commit()
        return True

    def reset_password(self, token, new_password):
        """Verify the new password for this user."""
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except (BadSignature, SignatureExpired):
            return False
        if data.get('reset') != self.id:
            return False
        self.password = new_password
        db.session.add(self)
        db.session.commit()
        return True

    @staticmethod
    def generate_fake(count=100, **kwargs):
        """Generate a number of fake users for testing."""
        from sqlalchemy.exc import IntegrityError
        from random import seed, choice
        from faker import Faker

        fake = Faker()
        roles = Role.query.all()

        seed()
        for i in range(count):
            u = User(
                first_name=fake.first_name(),
                last_name=fake.last_name(),
                email=fake.email(),
                password='password',
                confirmed=True,
                role=choice(roles),
                **kwargs)
            db.session.add(u)
            try:
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

    def __repr__(self):
        return '<User \'%s\'>' % self.full_name()


class AnonymousUser(AnonymousUserMixin):
    def can(self, _):
        return False

    def is_admin(self):
        return False


login_manager.anonymous_user = AnonymousUser


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/user/__init__.py
from app.user.views import user  # noqa

app/user/views.py
from flask import Blueprint, render_template, url_for, redirect

from app import db
from flask_login import (current_user, login_required)
from app.models import User, Schedule_year, Shift, User_schedule, Timeoff

user = Blueprint('user', __name__)


@user.route('/')
@login_required
def index():
    user = User.query.filter_by(id=current_user.id).first()
    schedules = User_schedule.query.filter_by(user=user)
    return render_template('user/index.html', user=user, schedules=schedules)

@user.route('/schedule/<int:schedule_id>')
@login_required
def schedule(schedule_id):
    user = User.query.filter_by(id=current_user.id).first()
    schedule = User_schedule.query.filter_by(user=user).filter_by(id=schedule_id).first()
    if schedule is None:
        return redirect(url_for('user.index'))
    return render_template('user/schedule.html', user=user, schedule=schedule)


@user.route('/shift_info')
@login_required
def shift_info():
    user = User.query.filter_by(id=current_user.id).first()
    schedule = db.session.query(User_schedule).join(
        Schedule_year, User_schedule.year).filter(
            Schedule_year.iscurrent).filter(
                User_schedule.user == user).first()
    if schedule is None:
        return redirect(url_for('user.index'))
    else:
        shifts = Shift.query.filter_by(schedule=schedule).all()
        return render_template(
            'user/shift_info.html', user=user, shifts=shifts)


@user.route('/timeoff_info')
@login_required
def timeoff_info():
    user = User.query.filter_by(id=current_user.id).first()
    schedule = User_schedule.query.filter_by(user=user).filter_by(
        active=True).first()
    if schedule is None:
        return redirect(url_for('user.index'))
    else:
        timeoff = Timeoff.query.filter_by(schedule=schedule).all()
        return render_template(
            'user/timeoff_info.html', user=user, timeoff=timeoff)

app/templates/user/index.html
{% extends 'layouts/user.html' %}

{% block user %}
    <table class="ui compact definition table">
        <tr><td>Start Date</td><td>{{ user.start_date }}</td></tr>
        <tr><td>Team</td><td>{{ user.team.name }}</td></tr>
        <tr><td>Full name</td><td>{{ '%s %s' % (user.first_name, user.last_name) }}</td></tr>
        <tr><td>Email address</td><td>{{ user.email }}</td></tr>
        <tr><td>Phone</td><td>{{ user.phone }}</td></tr>
    </table>
    <table class="ui compact definition selectable table">
        <thead>
            <tr>
                <th></th>
                <th>Available Vacation</th>
                <th>Personal Days Used</th>
                <th>Parttime</th>
                <th>Averaging</th>
                <th>Shift Length</th>
            </tr>
        </thead>
        <tbody>
            {% for s in schedules %}
                {% if s.year.iscurrent %}
                    <tr onclick="window.location.href ='{{url_for('user.schedule', schedule_id=s.id)}}'">
                {% else %}
                    <tr class="inactive" onclick="window.location.href ='{{url_for('user.schedule', schedule_id=s.id)}}'">
                {% endif %}
                {% if s.shiftlength > 8 %}
                <td class="ui icon" data-tooltip="Vacation has been scaled down to accomodate {{s.shiftlength}} hour shifts. Personal days are still represented as 8 hours">
                    {{s.year.year}}
                    <i class="question circle icon"></i>
                {% else %}
                <td class="ui icon">
                    {{s.year.year}}
                {% endif %}
                </td>
                <td>{{s.available_vacation}}</td>
                <td>{{s.used_personal}}</td>
                <td>{{s.isparttime}}</td>
                <td>{{s.isaveraging}}</td>
                <td>{{s.shiftlength}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/user/schedule.html
{% extends 'layouts/user.html' %}

{% block user %}
    <div class="row">

    </div>
    <table class="ui compact definition table">
        <tr><td>Carried Vacation Days</td><td>{{ schedule.carriedvacation }}</td></tr>
        <tr><td>Entitled Vacation Days</td><td>{{ schedule.entitledvacation }}</td></tr>
        <tr><td>Entitled Personal Days</td><td>{{ schedule.entitledpersonal }}</td></tr>
        <tr><td>Part-Time</td><td>{{ schedule.ispartime }}</td></tr>
        <tr><td>Averaging</td><td>{{ schedule.isaveraging }}</td></tr>
        <tr><td>Normal Shift Length</td><td>{{ schedule.shiftlength }}</td></tr>
    </table>
{% endblock %}

app/templates/user/shift_info.html
{% extends 'layouts/user.html' %}

{% block user %}
    <div class="row">
    </div><br>
        <div class="row">
            <div id="s" class="four fields">
                <div class="ui input date_picker"><input placeholder="Start" type="text" id="min" /></div><div class="ui input date_picker"><input placeholder="End" type="text" id="max" /></div>
            </div><br>
            <div class="six fields">
                <div class="ui label">
                  Total Hours
                  <div id="hours" class="detail"></div>
                </div>
                <div class="ui blue label">
                  IC
                  <div id="ic" class="detail"></div>
                </div>
                <div class="ui orange label">
                  Paid OT
                  <div id="paid" class="detail"></div>
                </div>
                <div class="ui yellow label">
                  Banked OT
                  <div id="banked" class="detail"></div>
                </div>
                <div class="ui purple label">
                  Training
                  <div id="training" class="detail"></div>
                </div>
            </div>
        </div><br>
        <div>
            <table class="ui celled selectable table shift_records_table">
                <thead>
                    <tr>
                        <th hidden>hhours</th>
                        <th>Day<i class="caret down icon"></i></th>
                        <th hidden>Employee<i class="caret down icon"></i></th>
                        <th>Start<i class="caret down icon"></i></th>
                        <th>End<i class="caret down icon"></i></th>
                        <th>Team<i class="caret down icon"></i></th>
                        <th hidden>Role<i class="caret down icon"></i></th>
                        <th hidden>IC<i class="caret down icon"></i></th>
                        <th hidden>Banked OT<i class="caret down icon"></i></th>
                        <th hidden>Paid OT<i class="caret down icon"></i></th>
                        <th hidden>Comments<i class="caret down icon"></i></th>
                        <th hidden>Training</th>
                    </tr>
                </thead>
                <tbody>
                {% for s in shifts %}
                    <tr>
                        <td hidden>{{ s.hours }}</td>
                        <td>{{ s.day }}</td>
                        <td hidden>{{ s.schedule.user.first_name}} {{ s.schedule.user.last_name[0] }}</td>
                        <td>{{ s.start_time }}</td>
                        <td>{{ s.end_time }}</td>
                        <td>{{ s.schedule.user.team.name}}</td>
                        <td hidden>{{ s.schedule.user.role.name}}</td>
                        <td hidden>{{ s.isic }}</td>
                        <td hidden>{{ s.otbanked }}</td>
                        <td hidden>{{ s.otpaid }}</td>
                        <td hidden>{{ s.comment }}</td>
                        <td hidden>{{ s.training }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready( function () {
        $('.shift_records_table').DataTable({
            createdRow: function( row, data, dataIndex){
                if( data[7] == `True`){
                    $(row).addClass('ic');
                }

                if( data[8] == `True`){
                    $(row).addClass('banked');
                }

                if( data[9] == `True`){
                    $(row).addClass('paid');
                }

                if( data[11] == `True`){
                    $(row).addClass('training');
                }
            },
            drawCallback: function( settings ) {
                var api = new $.fn.dataTable.Api( settings );

                $('#hours').text(calcTotalHours(api.rows( {page:'current'} ).data()));
                $('#ic').text(calcTotalHours(api.rows( {page:'current'} ).data().filter(function(value){
                        if ( value[7] == 'True' )
                        {
                            return true;
                        }
                        return false;
                })));
                $('#banked').text(calcTotalHours(api.rows( {page:'current'} ).data().filter(function(value){
                        if ( value[8] == 'True' )
                        {
                            return true;
                        }
                        return false;
                })));
                $('#paid').text(calcTotalHours(api.rows( {page:'current'} ).data().filter(function(value){
                        if ( value[9] == 'True' )
                        {
                            return true;
                        }
                        return false;
                })));
                $('#training').text(calcTotalHours(api.rows( {page:'current'} ).data().filter(function(value){
                        if ( value[11] == 'True' )
                        {
                            return true;
                        }
                        return false;
                })));
            },
            "paging": false,
            "dom": "<'ui stackable grid'"+
                        "<'row dt-table'"+
                            "<'sixteen wide column'tr>"+
                        ">"+
                    ">",
            initComplete: function () {
                createRangeSelector(this)
                }
            })
        })


    $.fn.dataTable.ext.search.push(
        function( settings, data, dataIndex ) {
            var min = new Date($('#min').val());
            var max = new Date($('#max').val());
            var data = new Date(data[1]);
            if ( ( isNaN( min ) && isNaN( max ) ) ||
                 ( isNaN( min ) && data <= max ) ||
                 ( min <= data   && isNaN( max ) ) ||
                 ( min <= data   && data <= max ) )
            {
                return true;
            }
            return false;
        }
    );

    function calcTotalHours(data){
      total = 0

      data.each(function(d){
        total += parseInt(d[0])
      })
      return total
    }

    function filterByDateByOTPaid(value){
      if ( filterByDate(value) && value[6] == 'True')
      {
          return true;
      }
      return false;
    }

    function createRangeSelector(dt){
        $('#min').val(moment().subtract(30, 'days').format('MM-D-YYYY'))
        $('#max').val(moment().format('MM-D-YYYY'))
        dt.api().draw()
        $('#min, #max').blur(function() {
            dt.api().draw();
        })
    }
</script>
{% endblock %}

app/templates/user/timeoff_info.html
{% extends 'layouts/user.html' %}

{% block user %}
    <div class="row">

    </div>
    <table class="ui celled sortable selectable table user_records_table">
        <thead>
            <tr>
                <th>Day</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody>
        {% for t in timeoff %}
            <tr>
                <td>{{ t.day }}</td>
                <td>{{ t.type.name }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}